import Footer from './components/Footer';
import Header from './components/Header/Header';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'PapaShop',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body>
				<Header />
				<main className={`${inter.className} min-h-[70vh]`}>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
